#!/usr/bin/env bash
# Script that installs and configures HAproxy load balancer on my lb-01 server 

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update
sudo apt-get -y install haproxy=2.5.\*
sudo chown -R "$USER":"$USER" /etc/default/haproxy
sudo chown -R "$USER":"$USER" /etc/haproxy/haproxy.cfg

echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 307320-web-01 54.144.86.135 check\n\tserver 307320-web-02 52.3.241.250 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
