#!/usr/bin/env bash
# Script to configure Nginx to listen on port 80

sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
nginx -t && systemctl reload nginx || systemctl start nginx
