#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes.

# Initialize hour and minute counters
hour=0
while [ "$hour" -lt 13 ];
do
	echo "Hour: $HOURS"
    	MINUTES=1
    	while [ $MINUTES -lt 60 ]
    	do
        	echo $MINUTES
		let MINUTES+=1
    	done
    	let HOURS+=1
done
